/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/binghatti.theme.ts
 * Command: astryx theme build src/theme/binghatti.theme.ts
 * CLI: @astryxdesign/cli@0.5.3
 * Core: @astryxdesign/core@0.5.3
 */

/// <reference path="./binghatti.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const binghattiTheme: DefinedTheme;
