import coreWebVitals from 'eslint-config-next/core-web-vitals'
import nextTypescript from 'eslint-config-next/typescript'

/**
 * Flat config, natively.
 *
 * This used to go through `FlatCompat` from `@eslint/eslintrc`, which is the
 * bridge for configs written in the old `extends` format. `eslint-config-next`
 * 16 ships flat configs directly - each entry point exports a `Linter.Config[]`
 * - so the bridge is not just unnecessary now, it FAILS: running a native flat
 * config back through the compatibility layer produced
 *
 *   TypeError: Converting circular structure to JSON
 *     --- property 'react' closes the circle
 *
 * which is a stack trace inside eslintrc rather than anything about this
 * project's rules. Worth recording because the error names neither the config
 * nor the upgrade that caused it.
 */
const config = [
  {
    ignores: [
      '.next/**',
      'node_modules/**',
      'next-env.d.ts',
      /*
       * GENERATED by `astryx theme build` from src/theme/binghatti.theme.ts,
       * and listed by exact name rather than as `src/theme/**` so the SOURCE
       * next to them - binghatti.theme.ts, fonts.ts, faces.ts - stays linted.
       *
       * The rule this trips is real, not cosmetic: the generated .d.ts opens
       * with a triple-slash reference to its own variants file, which
       * @typescript-eslint/triple-slash-reference forbids. It cannot be fixed
       * where it appears - the file is overwritten on every build, and CI's
       * `theme:check` gate fails if it is edited by hand - so the choice is
       * to ignore these four paths or to hold a lint error open forever.
       */
      'src/theme/binghatti.css',
      'src/theme/binghatti.js',
      'src/theme/binghatti.d.ts',
      'src/theme/binghatti.variants.d.ts',
    ],
  },
  ...coreWebVitals,
  ...nextTypescript,
]

export default config
